from __future__ import annotations

import json
import os
import smtplib
from dataclasses import asdict
from email.message import EmailMessage
from pathlib import Path

from jinja2 import Template

from trading_system.alerts.rules import Alert
from trading_system.engine.backtester import BacktestResult


HTML_TEMPLATE = Template(
    """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>End-of-Day Trading Report</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 980px; margin: 32px auto; padding: 0 18px; color: #172033; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; }
    .card { border: 1px solid #d9dfeb; border-radius: 12px; padding: 16px; background: #f8fafc; }
    .value { font-size: 1.55rem; font-weight: 700; margin-top: 8px; }
    table { width: 100%; border-collapse: collapse; margin-top: 14px; }
    th, td { border-bottom: 1px solid #e5e7eb; padding: 9px; text-align: left; }
    .high { color: #b42318; font-weight: 700; }
    .medium { color: #b54708; font-weight: 700; }
    .muted { color: #667085; }
  </style>
</head>
<body>
  <h1>End-of-Day Trading Report</h1>
  <p class="muted">Strategy: {{ strategy }} | Period: {{ start }} to {{ end }}</p>
  <div class="grid">
    <div class="card"><div>Total return</div><div class="value">{{ pct(metrics.total_return) }}</div></div>
    <div class="card"><div>Sharpe ratio</div><div class="value">{{ num(metrics.sharpe_ratio) }}</div></div>
    <div class="card"><div>Max drawdown</div><div class="value">{{ pct(metrics.max_drawdown) }}</div></div>
    <div class="card"><div>Trades</div><div class="value">{{ metrics.trade_count }}</div></div>
    <div class="card"><div>Ending equity</div><div class="value">${{ money(metrics.ending_equity) }}</div></div>
  </div>

  <h2>Alerts</h2>
  {% if alerts %}
  <table>
    <thead><tr><th>Severity</th><th>Rule</th><th>Symbol</th><th>Message</th></tr></thead>
    <tbody>
      {% for alert in alerts %}
      <tr><td class="{{ alert.severity }}">{{ alert.severity|upper }}</td><td>{{ alert.rule }}</td><td>{{ alert.symbol }}</td><td>{{ alert.message }}</td></tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}<p>No active alerts.</p>{% endif %}

  <h2>Latest trades</h2>
  {{ trades_html | safe }}
  <p class="muted">Generated by the trading-system portfolio project. For research and demonstration only.</p>
</body>
</html>
"""
)


def generate_eod_report(
    result: BacktestResult,
    alerts: list[Alert],
    output_dir: str | Path = "artifacts/eod",
) -> tuple[Path, Path]:
    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    trades = result.trades.tail(20)
    trades_html = trades.to_html(index=False, border=0) if not trades.empty else "<p>No trades.</p>"
    html = HTML_TEMPLATE.render(
        strategy=result.strategy_name,
        start=result.summary()["start"],
        end=result.summary()["end"],
        metrics=result.metrics,
        alerts=[alert.to_dict() for alert in alerts],
        trades_html=trades_html,
        pct=lambda value: f"{float(value):.2%}",
        num=lambda value: f"{float(value):.2f}",
        money=lambda value: f"{float(value):,.2f}",
    )
    html_path = root / "eod_report.html"
    json_path = root / "eod_report.json"
    html_path.write_text(html, encoding="utf-8")
    json_path.write_text(
        json.dumps(
            {
                "summary": result.summary(),
                "alerts": [asdict(alert) for alert in alerts],
                "latest_trades": trades.to_dict("records"),
            },
            indent=2,
            default=str,
        ),
        encoding="utf-8",
    )
    return html_path, json_path


def send_report_email(subject: str, html_path: str | Path, recipient: str) -> None:
    host = os.getenv("SMTP_HOST")
    port = int(os.getenv("SMTP_PORT", "587"))
    username = os.getenv("SMTP_USERNAME")
    password = os.getenv("SMTP_PASSWORD")
    sender = os.getenv("SMTP_SENDER", username or "trading-system@example.com")
    if not host or not username or not password:
        raise RuntimeError("SMTP_HOST, SMTP_USERNAME, and SMTP_PASSWORD must be configured")

    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = sender
    message["To"] = recipient
    message.set_content("Open this email in an HTML-compatible client to view the report.")
    message.add_alternative(Path(html_path).read_text(encoding="utf-8"), subtype="html")

    with smtplib.SMTP(host, port, timeout=20) as client:
        client.starttls()
        client.login(username, password)
        client.send_message(message)
